/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as AuthRegisterImport } from './routes/auth/register';
import { Route as AuthLoginImport } from './routes/auth/login';
import { Route as AdminUsersImport } from './routes/admin/users';
import { Route as AdminKycSubmissionsImport } from './routes/admin/kyc-submissions';
import { Route as AdminDashboardImport } from './routes/admin/dashboard';
import { Route as AdminAuthLoginImport } from './routes/admin/auth/login';

// Create/Update Routes

const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any);

const AuthRegisterRoute = AuthRegisterImport.update({
    id: '/auth/register',
    path: '/auth/register',
    getParentRoute: () => rootRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => rootRoute,
} as any);

const AdminUsersRoute = AdminUsersImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => rootRoute,
} as any);

const AdminKycSubmissionsRoute = AdminKycSubmissionsImport.update({
    id: '/admin/kyc-submissions',
    path: '/admin/kyc-submissions',
    getParentRoute: () => rootRoute,
} as any);

const AdminDashboardRoute = AdminDashboardImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => rootRoute,
} as any);

const AdminAuthLoginRoute = AdminAuthLoginImport.update({
    id: '/admin/auth/login',
    path: '/admin/auth/login',
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        '/admin/dashboard': {
            id: '/admin/dashboard';
            path: '/admin/dashboard';
            fullPath: '/admin/dashboard';
            preLoaderRoute: typeof AdminDashboardImport;
            parentRoute: typeof rootRoute;
        };
        '/admin/kyc-submissions': {
            id: '/admin/kyc-submissions';
            path: '/admin/kyc-submissions';
            fullPath: '/admin/kyc-submissions';
            preLoaderRoute: typeof AdminKycSubmissionsImport;
            parentRoute: typeof rootRoute;
        };
        '/admin/users': {
            id: '/admin/users';
            path: '/admin/users';
            fullPath: '/admin/users';
            preLoaderRoute: typeof AdminUsersImport;
            parentRoute: typeof rootRoute;
        };
        '/auth/login': {
            id: '/auth/login';
            path: '/auth/login';
            fullPath: '/auth/login';
            preLoaderRoute: typeof AuthLoginImport;
            parentRoute: typeof rootRoute;
        };
        '/auth/register': {
            id: '/auth/register';
            path: '/auth/register';
            fullPath: '/auth/register';
            preLoaderRoute: typeof AuthRegisterImport;
            parentRoute: typeof rootRoute;
        };
        '/admin/auth/login': {
            id: '/admin/auth/login';
            path: '/admin/auth/login';
            fullPath: '/admin/auth/login';
            preLoaderRoute: typeof AdminAuthLoginImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/admin/dashboard': typeof AdminDashboardRoute;
    '/admin/kyc-submissions': typeof AdminKycSubmissionsRoute;
    '/admin/users': typeof AdminUsersRoute;
    '/auth/login': typeof AuthLoginRoute;
    '/auth/register': typeof AuthRegisterRoute;
    '/admin/auth/login': typeof AdminAuthLoginRoute;
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/admin/dashboard': typeof AdminDashboardRoute;
    '/admin/kyc-submissions': typeof AdminKycSubmissionsRoute;
    '/admin/users': typeof AdminUsersRoute;
    '/auth/login': typeof AuthLoginRoute;
    '/auth/register': typeof AuthRegisterRoute;
    '/admin/auth/login': typeof AdminAuthLoginRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/': typeof IndexRoute;
    '/admin/dashboard': typeof AdminDashboardRoute;
    '/admin/kyc-submissions': typeof AdminKycSubmissionsRoute;
    '/admin/users': typeof AdminUsersRoute;
    '/auth/login': typeof AuthLoginRoute;
    '/auth/register': typeof AuthRegisterRoute;
    '/admin/auth/login': typeof AdminAuthLoginRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/admin/dashboard'
        | '/admin/kyc-submissions'
        | '/admin/users'
        | '/auth/login'
        | '/auth/register'
        | '/admin/auth/login';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/'
        | '/admin/dashboard'
        | '/admin/kyc-submissions'
        | '/admin/users'
        | '/auth/login'
        | '/auth/register'
        | '/admin/auth/login';
    id:
        | '__root__'
        | '/'
        | '/admin/dashboard'
        | '/admin/kyc-submissions'
        | '/admin/users'
        | '/auth/login'
        | '/auth/register'
        | '/admin/auth/login';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    AdminDashboardRoute: typeof AdminDashboardRoute;
    AdminKycSubmissionsRoute: typeof AdminKycSubmissionsRoute;
    AdminUsersRoute: typeof AdminUsersRoute;
    AuthLoginRoute: typeof AuthLoginRoute;
    AuthRegisterRoute: typeof AuthRegisterRoute;
    AdminAuthLoginRoute: typeof AdminAuthLoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AdminDashboardRoute: AdminDashboardRoute,
    AdminKycSubmissionsRoute: AdminKycSubmissionsRoute,
    AdminUsersRoute: AdminUsersRoute,
    AuthLoginRoute: AuthLoginRoute,
    AuthRegisterRoute: AuthRegisterRoute,
    AdminAuthLoginRoute: AdminAuthLoginRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/dashboard",
        "/admin/kyc-submissions",
        "/admin/users",
        "/auth/login",
        "/auth/register",
        "/admin/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/admin/kyc-submissions": {
      "filePath": "admin/kyc-submissions.tsx"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/admin/auth/login": {
      "filePath": "admin/auth/login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
